replicaCount: 2

image:
  repository:  172.17.0.1:8085/codeexperts
  tag: 70
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: nexus-secret
  
service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: nginx
  host: fastapi.local
  path: /
  pathType: Prefix

resources: {}
